"camera": {
    "camera_id": 0,
    "window_size": [1200, 800],
}

"process": {
    "field_width": 540, # must be divisible by 9
    "patch_size": 64,
    "nonzeros_treshold": 0.01,
    "contrast_treshold": 0.35,
    "nonzeros_range": 0.5, #[0;1]
    "patch_truncate": 0.005, #[0;1]
    "patch_binarization": 0.7, #[0;1]
    "utils": {
        "line_thick": 2,
        "mode": 'main', # binary, max_contour, homography, tensor, predictions, predictions_homography, main
    }  
}

"nn": {
    "train_batch_size": 512,
    "validation_batch_size": 1024,
    "learning_rate": 1e-3,
    "weight_decay": 1e-3,
}
