"camera": {
    "camera_id": 0,
    "window_size": [1200, 800],
}

"process": {
    "field_width": 540, # must be divisible by 9
    "patch_size": 80,
    "nonzeros_treshold": 0.01,
    "contrast_treshold": 0.35,
    #"threshold": 0.4,
    "utils": {
        "line_thick": 2,
        "mode": 'predictions_homography', # binary, max_contour, homography, tensor, predictions, predictions_homography, main
    }  
}

"nn": {
    "learning_rate": 1e-3,
    "batch_size": 256,
    "weight_decay": 1e-3,
}
